# db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/team_h
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}   


# mybatis config

mybatis:
  type-aliases-package: com.green.boardver2.model
  mapper-locations: mapper/**/*.xml


# swagger
springdoc:
  swagger-ui:
    path: /swagger.html


file:
  dir: /download/
